/* eslint-disable no-restricted-globals */
// service-worker.js

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Clean up outdated caches
cleanupOutdatedCaches();

// Precache all assets generated by Next.js
precacheAndRoute(self.__WB_MANIFEST || []);

// 📌 24-Hour Caching for News API (Network-First)
registerRoute(
  ({ url }) => url.origin === 'https://thevaluechainng.com',
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 60 * 60 * 24, // Cache expires after 24 hours
      }),
    ],
  })
);

// 📌 Image Caching (Cache-First, No Expiration)
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'image-cache',
  })
);

// 📌 PDF Caching (Cache-First, Never Expires)
const PDF_API_URL = process.env.ECOPY_API_URL || 'https://your-api.com';

registerRoute(
  ({ request, url }) =>
    request.destination === '' && url.href.startsWith(PDF_API_URL) && url.pathname.endsWith('.pdf'),
  new CacheFirst({
    cacheName: 'pdf-cache',
  })
);

// 📌 Offline Fallback for failed requests
registerRoute(
  ({ url }) => true,
  new NetworkFirst({
    cacheName: 'fallback-cache',
    networkTimeoutSeconds: 5,
    plugins: [
      {
        cacheWillUpdate: async ({ response }) => {
          if (!response || response.status !== 200) {
            return new Response('You are offline!');
          }
          return response;
        },
      },
    ],
  })
);

// Listen for install and activate events
self.addEventListener('install', (event) => {
  console.log('Service Worker: Installed');
});

self.addEventListener('activate', (event) => {
  console.log('Service Worker: Activated');
});
